language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - selarslann@mail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: R2AS8sNH+8cR024xWSuqLuogAyzY6GTgMVBBjuMlSJPDkRq/73Az1ZXJ+52Cgpx115SX2Zfz+lGDLCuq5yL7eYHe+GNaW4KiLErfh0QCed9ZlRvNRVK5B4OfKv+fNlW8Dd/9V5LYYJRMuE3QWuIB3bv88khPPQ50EngGXd+F4sJ90EkKdAkw3jMwQYBbG0wBv3bCU/953RNC1urr+9kOwk5wC+/1bbi+mZEUm5lhiXO1GyL2Kqt62yPZ6HU/2jbK7dL11xjJQfaa5FMb7w/RydGnuM4ocZpyWztjE++TxnQFvAz6KO9dCqWOEjOYi0TTJ9wBLyC+CP00tSU7Jy+KWT0dwv6EtB1jpj5+C7Yc/y9nmjP0bhZz9fzY6HYvUSVMA4Qmm3ocfrLrqVqF1IUv7SbS+yag4qvx4noQ5dXvsnEnJEoBVLTRTTg4ppQ0DDp+cS1ySbDeV8SYYLfCf5U4EGOqEp5iJiXJ5Ek2WgVvpuh3idkVUumcovv9cwtIX3YV11jHeLWDWI4k8Ji7JH1gJQog+NN/kzkFG/PXAXVR7PND8Puggo6rElqUHS3Vyflgo1ZZkfGulh+Z/KNmgwGh/k0ob6oS7f3aEuX4POEBEf/QTSKD/5jwDjuZRUbZBB3FRjfC7X8+F0/A4gnUmdrguFBBwx7wg3YXVRUeIqdq7Fk=
  - secure: f/4YKhikWvw+5xNbgR+LN/6dOpuNWiY6762QDfprRzpDE9Up4EYth4wVE3DKBPgbOvAx+yoZPNScctI2NWB09atKPMP3AX5dudpicezC0FDrHgQVptE8ywPcg1wOA6DBevX13b37MowXtBeUd4cP4UAeHE03USOnMv/ckRBXfHxQvhBB4JCrf5UAXPg2IcCWYYXrC/U6V2qadw6Ybua7ARijF+ImcJfjQEy4+2CmC4WwX29GxgE2PXep/G/t3ERBYJpbUPqtL9aw/GGZ6UzjinVWWWDO2kb5g5lfmxZr1U2YEy9iGG0QP8/p8/Mek/vLRnEYb3TChTQMZWZZDwi2vrNgfWi/UiVt6bx+Xm2Oh90/qGlfFbflTDTepatU5SeaCIL+7HR4O0cf5hdumRtgt75DDgUU1rtlPoeohD1xXZIGBK7Yprn0A6grhT0JFzAix9eekEnQtYLMO53akRUA0IVctjRw1p6AUAV2RN9WB0IZ2ndKBk9umxJrUjZ8ciNSfhWMY0aQVv+Fd4O2uSRHGxOxUEivrl5tyAS2TxhOMve8wLSz/SDoNoQY1EOzuqjPHnCd1DFQIDGmfkK/1WDMnMpKIj3rDzWroGHxy08GJiiH/L8+vnXzG9zEzIdr6j36g6cGSKBBAJZSMskeqE/JpnJQVrfxKlFJi7R14Fb4zDo=
  - secure: PDJsxAxNGo5/dB3gq5M1NRFWgfAiSdg8wiNqY5J78IS8Ys0OOZXOQ5LiU3KvH9gWX7tNNuqJiroUrMEmo48WKIo5YsfXchwZkPCf76Rru3+Np1Y51KBJGyon8yxs6Zswm/uScf92+J+DfULRMBFaNp90XQKVjCdDNP5iUINcROKsO8tF8UqX5tuJqdaIHlNbVTaPg56hiK2tD7OzqvUEV/BFF5Y+co86N+6v9GQmeMDQldOKuPrWdG7glAqYRs1CimWGTotTDu8hF43Hz7hcUy82/mH3zk50AfGU5s2CFMYsSYU8yDOVIy3xaFLGwj3vDjqpFk7gx0IxAwXLIXMGmfHe4cesXlKDEWXm+Pf1fVI7gm1d3w0h/WQdTJIhW4rGsS6gxBTXHJe7vTWBEw++pPDPivsneAkFwvpfS56MhDFnWvAdVS+8AXzER+X9MypPDKmsPkuNhgIp8F/Etyht/sVP7qnS0lJX9aY3tTKkfvhXYGxnsmI1VclKO41uePys9NMz4ILBDsrSzFZkgSiNFNJjuO2Rf17GvAgfYhPfIM7PFE+hZo/CdwROoZjQJUnruuJ4s80F5pHHCrEmFma4OnEK9qBp8BAtg6Uy7mpc4CklTpxPLSW7K37wW1wUro6Slkz7hlPLPlcc2vGGBgzjYQRtQvCN5/NM0C5bjO9u5XI=
  - secure: id3yxru1wkGOWMFGafs0L1jeZY6M5nVWw0n//BMmCKcwOPVUZMd/VNZ3GvgxFPLc4e8LWQaK6qhTQGgb6u8zU1GOxb0iFXEo8DYAET3NWxbHMoNq2llA3edJpXfs9X9jGML4z0bYJFoyvV1KIN+afl6UBDltG0/h5QWcHI6ilFuh8lSEVvnJxyQ+eQnZeJkjk5qMOUz7mWDjPhnY6EZXmfq2JAKHWxFHqtwVgPfMRHI0K9ZKVWWVyV3gNmL1EqCBY4+fD1mplFbNRi2iKjad8CI2XoUj+L5jtiVWSp9O+v2cWYJ1lD9TLmZA3oJELrw4Tr4bIJ4pGf/cEwgnY9tVDJqraw6u9eaYIfr9c1aik8tiqnLNFeh/dWKuFzJUy0nuBfPyVgVWgMmpEUFMcJ/PHBJHlG6uFKU+zI0iunGi+S0+hqbm92BqZYavxHz8MO3+LpnnwoNC8BPd2BTxwaXczN1Qcp/5ocDW4m9PkHmaPiU9eG6mSVwZLAjbSaf6Bu51/YKuSPqzV7mAP7FoLk4zJTZAWr0XwXUUdeZrcP+/uV2oWAfbFdLcLCIBgks06j6oAMkWjiKLMRejvw/AyynuC5kqJzEsudee7oUVb7CrV6N42+FF17Bp+/IdLIlQFt61FhZrOe6OKVxiXCmwfnlcp5CyAi3UIWs5MxVK+Qr/RZM=
before_install:
- env
- gem install travis -v 1.8.5 --no-document
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=spmia10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=54.215.193.139
- export PLATFORM_TEST_NAME="spmia10-platform-tests"
#- update-alternatives --list java
#- export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
#- export PATH=$JAVA_HOME/bin:$PATH
#- javac --version
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
